### PR TITLE
[WIP] mssql

### PR DESCRIPTION
**Pull request by patricklee2**
install msodbcsql17
by customer request

### CODE REVIEW

**Comment by patricklee2** [comment]
https://msazure.visualstudio.com/Antares/_workitems/edit/4609062

**Comment by patricklee2** [comment]
install in oryx base image
https://github.com/microsoft/Oryx/blob/ffb5a357f007e86c4b2361533c4e4d0c9cce515d/images/runtime/php/Dockerfile.base.template#L85

**Comment by akrabat** [comment]
When will this be deployed to Azure as this is not fixed in a Linux/PHP App Service that I deployed today?

**Comment by patricklee2** [comment]
It should be deployed in July

**Pull request closed without merging**
