### PR TITLE
Added PHP 7.1

### PR DESCRIPTION
**Pull request by howlowck**
While PHP 7.1 is relatively new.  It is the latest stable version, and many popular frameworks and libraries are dependent on this version.  Example: [Doctrine DBAL's latest version](https://packagist.org/packages/doctrine/dbal) is 7.1+

Adding PHP 7.1 into the Azure Run Stack would greatly enhance the dev experience for modern PHP developers who wants to quickly get started with Azure Web App on Linux.

### CODE REVIEW

**Comment by howlowck** [comment]
This will also partially address Issue #1

**Comment by trixmc** [comment]
Merge it, pls

**Comment by patricklee2** [comment]
closed in favour of 7.2, 7.3

**Comment by howlowck** [comment]
Why is 7.1 excluded from the supported versions?

**Comment by patricklee2** [comment]
we already have 7.2 and 7.3, is there a reason you need 7.1 in particular?

**Comment by howlowck** [comment]
Simply for completion. 

Azure App Services is a platform.  we won't know why a customer needs a particular version of a language.. 
It might be for a legacy library version (an older version of Doctrine or Laravel, [where PHP 7.2 is incompatible with certain versions](https://github.com/laravel/framework/issues/20248)). Or they might have even more legacy software that they want to incrementally upgrade to 5.6 to 7.0 to 7.1

**Comment by patricklee2** [comment]
We'll add it if there is customer demand, Otherwise we don't want to support something that will soon be end of life.

**Pull request closed without merging**
